### ISSUE TITLE
Published papers

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#68]

**Comment by dragonfly90** [comment]
A famous book to describe python script like regular expression: Langtangen, Hans Petter. Python scripting for computational science. Vol. 3. Berlin, Heidelberg and New York: Springer, 2006.

**Comment by alannsp** [comment]
Thelwall, Mike. "A web crawler design for data mining." Journal of Information Science 27.5 (2001): 319-325. 
The processing of the text of web pages
in order to extract information can be expensive in terms of
processor time. Consequently a distributed design is proposed
in order to effectively use idle computing resources
and to help information scientists avoid the need to employ
dedicated equipment.

**Comment by alannsp** [comment]
Castillo, Carlos. "Effective web crawling." ACM SIGIR Forum. Vol. 39. No. 1. ACM, 2005.
This thesis
studies Web crawling at several different levels, ranging from the long-term goal of crawling important
pages first, to the short-term goal of using the network connectivity efficiently, including
implementation issues that are essential for crawling in practice.

**Comment by dragonfly90** [comment]
Grehan, Rick. "Pillars of Python: Web. py Web framework." InfoWorld IDG Retrieved January (2013).    Compare six web frameworks like web.py and Django

**Comment by alannsp** [comment]
add those in the readme
